version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - .db:/var/lib/postgresql/data

  alembic:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    command: >
      /bin/sh -c "
        until pg_isready -h postgres -U ${DB_USERNAME}; do
          echo 'Waiting for postgres...';
          sleep 2;
        done;
        alembic upgrade head
      "

  app:
    build:
      context: .
    depends_on:
      - alembic
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    command: >
      /bin/sh -c "
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
