"""add bussines_name

Revision ID: c21de1209b8b
Revises: be0a49d7b333
Create Date: 2024-11-13 20:45:01.519822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21de1209b8b'
down_revision: Union[str, None] = 'be0a49d7b333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'business_name')
    # ### end Alembic commands ###
